#ifndef __WIREDPLUGIN_H__
#define __WIREDPLUGIN_H__


#include <wx/wxprec.h>
#ifndef WX_PRECOMP
   #include <wx/wx.h>
#endif

// file used only for define INSTALL_PREFIX (generated by autotools)
#include "config.h"

#include "WiredPluginStartInfo.h"
#include "WiredPluginGui.h"
#include "WiredPluginAudio.h"

class WiredPluginStartInfo;
class WiredPluginGui;
class WiredPluginAudio;


////
// Current version of API
//
// this number increment only when methods or function of API are modified
//
#define WIRED_CURRENT_VERSION_API (2)


class		WiredPlugin : public WiredPluginGui, public WiredPluginAudio
{
 private:
  WiredPluginStartInfo	*StartInfo;

 public:
  WiredPlugin(WiredPluginStartInfo *parent)
    { StartInfo = parent; } : WiredPluginGui(parent) : WiredPluginAudio(parent);
  ~WiredPlugin();

  virtual void	 Load(WiredPluginData& Datas) {}
  virtual void	 Save(WiredPluginData& Datas) {}

  /* Called when host needs to show the plugin's help */
  virtual wxString GetHelpString() { return _("No help provided for this plugin"); }

  /* Returns the default name for the plugin */
  virtual wxString DefaultName() { return _("Rack"); }


  // Host info
  /* Returns the host product name */
  wxString	GetProductName();
  /* Returns the host product version */
  wxString	GetProductVersion();
};

#endif // __WIREDPLUGIN_H__
