#ifndef __WIREDCOREPLUGINS_H__
#define __WIREDCOREPLUGINS_H__


#include <wx/wxprec.h>
#ifndef WX_PRECOMP
   #include <wx/wx.h>
#endif

// file used only for define INSTALL_PREFIX (generated by autotools)
#include "config.h"

#include <list>
#include <vector>
#include "Sequencer.h"
#include "Rack.h"
#include "MainWindow.h"
#include "FileLoader.h"
#include "HelpPanel.h"
#include "HelpCtrl.h"
#include "OptionPanel.h"
#include "MidiThread.h"
#include "MidiController.h"
#include "MidiThread.h"


class WiredPlugin;



class	WiredCorePlugins
{
 private:
  int		_MidiType;
  int		_MidiController;
  int		_MidiValue;


  // The number of frames the event will start on next call to Process()
  long		_DeltaFrames;
  // The note length (usually 0, look for note off messages to know the end of a note
  long		_NoteLength;


 public:

  WiredCorePlugins();
  ~WiredCorePlugins();


  /**
   * Event related
   */
  void		SendMouseEvent(WiredPlugin* plugin, wxMouseEvent* event);


  void		SendKeyEvent(WiredPlugin* plugin, wxKeyEvent* event);


  void		SendPaintEvent(WiredPlugin* plugin, wxPaintEvent* event);


  void		UpdatePluginGui(WiredPlugin* plugin);


  /**
   * Basic info
   */

  /**
   * Get the host name
   * \return wxString name of Wired (basically "Wired")
   */
  wxString	GetProductName();

  /**
   * Get the host version
   * \return wxString version of Wired ("0.3.1", ..)
   */
  wxString	GetProductVersion();

  // long		GetBufferSize();
  //

  /**
   * Audio info
   */

  // double		GetSamplingRate();
  //

  float		GetBpm();


  int		GetSigDenominator();


  int		GetSigNumerator();


  double	GetSamplesPerMeasure();


  double	GetMeasurePerSample();


  long		GetCurAudioPos();


  double	GetCurrentPos();


  /**
   * Gui related
   */

  wxString	OpenFileLoader(wxString& title,
			       std::vector<wxString>* extensions,
			       bool addExts,
			       bool akai);


  wxString	SaveFileLoader(wxString& title,
			       std::vector<wxString>* extensions,
			       bool addExts);


  void		SendHelp(wxString& value);


  void		ShowOptionalView(WiredPlugin* plugin);


  void		CloseOptionalView(WiredPlugin* plugin);

  /**
   * Midi related
   */

  void		AddMidiPattern(WiredPlugin* plugin,
			       std::list<SeqCreateEvent*>* midi);


  void		ShowMidiController(WiredPlugin* plugin);


  int		GetLastMidiType();


  int		GetLastMidiController();


  int		GetLastMidiValue();


};

#endif // __WIREDCOREPLUGINS_H__
