#ifndef __WIREDPLUGIN_H__
#define __WIREDPLUGIN_H__


#include <wx/wxprec.h>
#ifndef WX_PRECOMP
   #include <wx/wx.h>
#endif

// file used only for define INSTALL_PREFIX (generated by autotools)
#include "config.h"

#include "WiredPluginStartInfo.h"
#include "WiredPluginGui.h"
#include "WiredPluginAudio.h"
#include "WiredPluginData.h"

class WiredPluginStartInfo;
class WiredPluginGui;
class WiredPluginAudio;
class WiredPluginData;

////
// Current version of API
//
// this number increment only when methods or function of API are modified
//
#define WIRED_CURRENT_VERSION_API (2)


class		WiredPlugin : public WiredPluginGui, public WiredPluginAudio, public WiredPluginData
{
 private:
  WiredPluginStartInfo*	_StartInfo;

 public:
  WiredPlugin(WiredPluginStartInfo* parent)
    { _StartInfo = parent; } : WiredPluginGui(parent) : WiredPluginAudio(parent);
  ~WiredPlugin();
};

#endif // __WIREDPLUGIN_H__
