#ifndef __WIREDPLUGIN_H__
#define __WIREDPLUGIN_H__


#include <wx/wxprec.h>
#ifndef WX_PRECOMP
   #include <wx/wx.h>
#endif

// file used only for define INSTALL_PREFIX (generated by autotools)
#include "config.h"

#include "WiredPluginStartInfo.h"
#include "WiredPluginGui.h"
#include "WiredPluginAudio.h"
#include "WiredPluginData.h"

//Needed by plugins
//#include "WiredMidiEvent.h"
#include "WiredPluginInstaller.h"


class WiredPluginStartInfo;
class WiredPluginInstaller;
class WiredPluginGui;
class WiredPluginAudio;
class WiredPluginData;


////
// Current version of API
//
// this number increment only when methods or function of API are modified
//
#define WIRED_CURRENT_VERSION_API (2)


class		WiredPlugin : public wxWindow, public WiredPluginGui, public WiredPluginAudio, public WiredPluginData
{
  friend class WiredCorePlugins;

 private:
  WiredPluginStartInfo*	_StartInfo;
  WiredPluginInstaller*	_CreatorInfo;

  WiredPluginStartInfo*	GetStartInfo();


 public:
  WiredPlugin(WiredPluginInstaller* creator, WiredPluginStartInfo* parent);
  ~WiredPlugin();


 public:
  /* info part */
  /*
  ** Return unique name of plugin instance ("loop sampler 4")
  */
  wxString&	GetName();

  /*
  ** Return name of plugin ("loop sampler")
  */
  wxString&	GetDefaultName();

  /*
  ** Set unique name of plugin instance ("loop sampler 4")
  */  
  void		SetName(wxString name);


  /*Gui part*/
  /* Ask the host application to call Update() whenever the main thread can process gui calls  */
  void		UpdatePluginGui();

  /*Audio part*/
  /* Used to know if a keyboard event occured. No need to overload */
  virtual void	OnKeyEvent(wxKeyEvent* event);
  /* Used to know if a mouse event occured. No need to overload */
  virtual void  OnMouseEvent(wxMouseEvent* event);
  /* Used to know if a paint event occured. No need to overload */
  virtual void  OnPaintEvent(wxPaintEvent* event);
  // User interface events
  bool		ShowMidiController();
 /* Shows plugin's optional view */
  void		ShowOptionalView();
  /* Closes plugin's optional view */
  void		CloseOptionalView();
  // Sequencer events
  /* Create a MIDI pattern containing a list of event in the host's sequencer */
  void		AddMidiPattern(std::list<SeqCreateEvent *>* midi);

};

#endif // __WIREDPLUGIN_H__
