#ifndef __WIREDPLUGINSTARTINFO_H__
#define __WIREDPLUGINSTARTINFO_H__


#include <wx/wxprec.h>
#ifndef WX_PRECOMP
   #include <wx/wx.h>
#endif
#include <wx/string.h>

// file used only for define INSTALL_PREFIX (generated by autotools)
#include "config.h"

class WiredPlugin;
class WiredPluginGui;
class WiredPluginAudio;
class WiredCorePlugins;
//class WiredPluginMgr;


/**
   * \dad Window ptr of plugin's parent
   * \pos Position
   * \size
   */

class	WiredPluginStartInfo
{
  //  friend WiredPluginMgr;
  friend class WiredPlugin;
  friend class WiredPluginGui;
  friend class WiredPluginAudio;
  friend class WiredCorePlugins;

 private:
  WiredCorePlugins*	_Core;
  wxString		_Version;
  wxWindow*		_Parent;
  wxPoint		_Pos;
  wxSize		_Size;



  WiredPluginStartInfo();
  ~WiredPluginStartInfo();


  WiredCorePlugins*	GetCore();
  wxString		GetVersion();
  wxWindow*		GetRack();
  wxPoint		GetPos();
  wxSize		GetSize();

 public:
};

#endif // __WIREDPLUGINSTARTINFO_H__
