#! /usr/bin/env python
# encoding: utf-8
# Daniel Moura, 2009 <oxe at oxesoft.com>

children = [
    'libs',
    'samplerate',
    'conf',
    'save',
    'dssi',
    'mixer',
    'wiredvideo',
    'undo',
    'editmidi',
    'audio',
    'midi',
    'data',
    'sequencer',
    'fileloader',
    'engine',
    'plugins',
    'xml',
    'codec',
    'redist',
    'gui'
    ]


def configure(conf):
    for i in children:
        conf.sub_config(i)

def build(bld):
    for i in children:
        bld.add_subdirs(i)
