#! /usr/bin/env python
# encoding: utf-8
# Daniel Moura, 2009 <oxe at oxesoft.com>

def configure(conf):
    pass

def build(bld):
    bld.new_task_gen(
        features = 'cxx cstaticlib',
        source = '''
            WiredExternalPluginMgr.cpp
            WiredExternalPlugin.cpp
            WiredExternalPluginLADSPA.cpp
            WiredExternalPluginGui.cpp
            ''',
        includes = '../engine ../redist ../save',
        export_incdirs = '.', 
        uselib = 'WX',
        uselib_local = 'WiredWidgets wiredxml',
        target = 'wireddssi')
