#! /usr/bin/env python
# encoding: utf-8
# Daniel Moura, 2009 <oxe at oxesoft.com>

def configure(conf):
    pass

def build(bld):
    bld.new_task_gen(
        features = 'cxx cstaticlib',
        source = '''
            SaveCenter.cpp
            WiredDocument.cpp
            ''',
        includes = '. ../engine',
        export_incdirs = '.',
        uselib_local = 'wiredxml',
        uselib = 'WX',
        target = 'save')
