#! /usr/bin/env python
# encoding: utf-8
# Daniel Moura, 2009 <oxe at oxesoft.com>

children = [
    'WiredAkai',
    'WiredWidgets']

def configure(conf):
    for i in children:
        conf.sub_config(i)

def build(bld):
    for i in children:
        bld.add_subdirs(i)
