#! /usr/bin/env python
# encoding: utf-8
# Daniel Moura, 2009 <oxe at oxesoft.com>

def configure(conf):
    pass

def build(bld):
    bld.new_task_gen(
        features = 'cxx cshlib',
        source = '''
            WahwahPlug.cpp
            ''',
        includes = '../../redist ../../save',
        target = 'WiredWahwah',
        uselib_local = 'WiredWidgets wiredxml',
        uselib = 'WX',
        install_path = '${PREFIX}/lib/plugins')
