#! /usr/bin/env python
# encoding: utf-8
# Daniel Moura, 2009 <oxe at oxesoft.com>

def configure(conf):
    pass

def build(bld):
    top_bld = bld.srcnode.abspath(bld.env)
    bld.new_task_gen(
        features = 'cxx cstaticlib',
        source = '''
            WiredCodec.cpp
            ''',
        includes = top_bld + ' ../save',
        export_incdirs = '.',
        uselib = 'WX',
        target = 'wiredcodec')
