#! /usr/bin/env python
# encoding: utf-8
# Daniel Moura, 2009 <oxe at oxesoft.com>

def configure(conf):
    pass

def build(bld):
    bld.new_task_gen(
        features = 'cxx cstaticlib',
        source = '''
            ControlChange.cpp
            Clavier.cpp
            EditMidi.cpp
            EditNote.cpp
            Key.cpp
            MidiAttr.cpp
            MidiPart.cpp
            Note.cpp
            RulerMidi.cpp
            ''',
        includes = '../engine ../redist ../midi ../gui ../sequencer ../save ../audio',
        export_incdirs = '.', 
        uselib_local = 'WiredWidgets wiredxml',
        uselib = 'WX',
        target = 'editmidi')
