#! /usr/bin/env python
# encoding: utf-8
# Daniel Moura, 2009 <oxe at oxesoft.com>

def configure(conf):
    pass

def build(bld):
    bld.new_task_gen(
        features = 'cxx cshlib',
        source = '''
        akai.cpp
        list.cpp
        ''',
        includes = '../include',
        export_incdirs = '../include',
        target = 'WiredAkai',
        install_path = '${PREFIX}/lib')
